$schema: https://json-schema.org/draft/2020-12/schema
title: ISO 19135 Register Item Class
type: object
properties:
  id: {type: string, format: uri}
  type: {const: "rim:RegisterItemClass"}
required: [id, type]
additionalProperties: true
